config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  root 'kittens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
    def index
        @kittens = Kitten.all

        respond_to do |format|
        format.html
        format.xml  { render :xml => @kittens }
        format.json { render :json => @kittens }
      end
    end

    def show
        @kitten = Kitten.find(params[:id])

        respond_to do |format|
        format.html
        format.xml  { render :xml => @kitten }
        format.json { render :json => @kitten }
      end
    end

    def new
        @kitten = Kitten.new
    end

    def edit
        @kitten = Kitten.find(params[:id])
    end

    def create
        @kitten = Kitten.new(kitten_params)
        if @kitten.save
            flash.notice = "Kitten '#{@kitten.name}' Created!"
            redirect_to kittens_path
        end
    end

    def update
        @kitten = Kitten.find(params[:id])
        @kitten.update(kitten_params)
        flash.notice = "Kitten '#{@kitten.name}' Updated!"

        redirect_to kitten_path(@kitten)
    end

    def destroy
        @kitten = Kitten.find(params[:id])
        @kitten.destroy

        flash.notice = "Kitten '#{@kitten.name}' Deleted!"
        redirect_to kittens_path
    end

    private
    def kitten_params
        params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for(@kitten) do |f| %>
<p>
<%= f.label :name %><br>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :age %><br>
<%= f.number_field :age %>
</p>
<p>
<%= f.label :cuteness %><br>
<%= f.number_field :cuteness %>
</p>
<p>
<%= f.label :softness %><br>
<%= f.number_field :softness %>
</p>
<%= f.submit%>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit an Article</h1>
<%= render partial: 'form' %>
<%= link_to "delete", kitten_path(@kitten), method: :delete, data: {confirm: "Really delete the kitten?"} %>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>

<ul id="kitten">
<% @kittens.each do |kitten|%>
<li>
<%= link_to kitten.name, kitten_path(kitten), class: 'kitten_name'%>
<%= link_to "delete", kitten_path(kitten), method: :delete, data: {confirm: "Really delete the kitten?"} %>
<%= link_to "edit", edit_kitten_path(kitten) %>
</li>
<% end %>
</ul>

app/views/kittens/new.html.erb
<h1>Create a New Kitten</h1>
<%= render partial: 'form' %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<br>
<h2> Age </h2>
<%= @kitten.age%>
<br>
<h2> Cuteness Score </h2>
<%= @kitten.cuteness%>
<br>
<h2> Softness Score </h2>
<%= @kitten.softness%>
<br>
<%= link_to "delete", kitten_path(@kitten), method: :delete, data: {confirm: "Really delete the kitten?"} %>
<%= link_to "edit", edit_kitten_path(@kitten) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= link_to "Create a New Kitten", new_kitten_path, class: "new_kitten"%>
  <%= link_to "All Kittens", kittens_path, class: "new_kitten"%>
  <p class="flash">
    <%= flash.notice %>
  </p>
    <%= yield %>
  </body>
</html>